name: AppDistribution

# Only deploy a beta to AppDistribution when we are preparing a new release
on:
  push:
    branches: 
      - release/**

jobs:
  deploy-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'

      - uses: subosito/flutter-action@master
        with:
          channel: stable

      - name: Fetch dependencies
        run: flutter pub get

      - name: Run Code Generate
        run: ./regenerate.sh
        
      - name: Setup Secrets
        run: |
          echo $GOOGLE_SERVICES_JSON | tee android/app/google-services.json
          echo $CONFIG_DART | tee lib/config.dart
          echo $KEY_PROPERTIES | tee android/key.properties
          echo $SIGNING_KEY | base64 --decode > android/distribution/aah.jks
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          CONFIG_DART: ${{ secrets.CONFIG_DART }}
          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}

      - name: Build APK
        run: flutter build apk
        
      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
        with:
          appId: ${{secrets.ANDROID_FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: 52inc,friends-&-family
          releaseNotesFile: android/distribution/release_notes.txt
          file: ${{ env.SIGNED_RELEASE_FILE }}
          
